
workflows:
  android-build:
    name: ALRC Radio Business
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
